
apiVersion: v1 #version of the API to use
kind: Pod #What kind of object we're deploying
metadata: #information about our object we're deploying
  name: tensorflow-pod
spec: #specifications for our object
  containers:
  - name: tensorflow-container #the name of the container within the pod
    image: tensorflow/tensorflow #which container image should be pulled
    ports:
    - containerPort: 80 #the port of the container within the pod
