kind: Namespace
apiVersion: v1
metadata:
  name: hollowteam
  labels:
    name: hollowteam
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: hollowteam
  labels:
    name: nginx
spec:
  containers:
  - name: nginx
    image: nginx
