kind: "Service"
apiVersion: "v1"
metadata:
  name: "external-web"
spec:
  ports:
    -
      name: "apache"
      protocol: "TCP"
      port: 80
      targetPort: 80 
---
  kind: "Endpoints"
  apiVersion: "v1"
  metadata:
    name: "external-web" 
  subsets: 
    -
      addresses:
        -
          ip: "172.104.184.40" #The IP Address of the external web server
      ports:
        -
          port: 30022 
          name: "apache"
