kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: default-restrictedrole
rules:
- apiGroups:
  - extensions
  resources:
  - podsecuritypolicies
  resourceNames:
  - default-restricted
  verbs:
  - use