apiVersion: batch/v1
kind: Job
metadata:
  name: hollow-curl
spec:
  template:
    spec:
      containers:
          - name: hollow-curl
            image: theithollow/hollowapp-blog:curl
            args:
            - /bin/sh
            - -c
            - curl https://theithollow.com
      restartPolicy: Never
  backoffLimit: 4