apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hollow-curl
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hollow-curl
            image: theithollow/hollowapp-blog:curl
            args:
            - /bin/sh
            - -c
            - curl https://theithollow.com
          restartPolicy: OnFailure